
gems:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - CNAME
  - Gemfile
  - README.md
permalink: /post/:year/:month/:day/:title
paginate: 8
repository: tmplat-extension/tmplat.com
title: tmplat
description: The homepage for the tmplat browser extension
url:  https://tmplat.com
author: neocotic
twitter:
  username: tmplat
social:
  name: tmplat
  links:
    - https://twitter.com/tmplat
    - https://github.com/tmplat-extension
lang: en
email: contact@tmplat.com
analytics_account: UA-40890665-1
sharethis_account: 59e4c79f2ef0440012cc2d2e
paypal_account: BGWG9R5LBNECY
support_url: https://tmplat.uservoice.com
translate_url: http://i18n.tmpl.at
extension:
  chrome:
    id: dcjnfaoifoefmnbhhlbppaebgnccfddf
    repo: tmplat-chrome
  dates:
    created: 2011-03-29
    published: 2011-04-11
    updated: 2015-11-08
  file:
    format: application/zip
    size: 178.9KB
  version: "1.2.9"
